// Generated by CoffeeScript 1.10.0
(function() {
  var $, _flash, buffer, flash, ipcRenderer, numify, stringify;

  ipcRenderer = require('electron').ipcRenderer;

  $ = require('./node_modules/jquery/dist/jquery.js');

  buffer = "";

  _flash = $('#flash');

  flash = function(content) {
    return _flash.html(content);
  };

  ipcRenderer.on('challenge', function(event, response) {
    console.log("Response: " + response);
    _flash.html(response);
    return _flash.attr("class", "user");
  });

  ipcRenderer.on('submission-response', function(event, response) {
    console.log(response.status);
    flash(response.message);
    if (response.status === 200) {
      _flash.attr("class", "success");
    } else if (response.status === 400) {
      _flash.attr("class", "error");
    }
    window.setTimeout(function() {
      return ipcRenderer.send('challenge-request');
    }, 2000);
  });

  ipcRenderer.send('challenge-request');

  numify = function(char) {
    return char.charCodeAt();
  };

  stringify = function(num) {
    return String.fromCharCode(num);
  };

  $(document).on('keypress', function(e) {
    var ascii;
    console.log(e.which);
    ascii = stringify(e.which);
    if (e.which >= numify("0") && e.which <= numify("9")) {
      buffer += ascii;
    } else if (e.which === 8) {
      buffer = buffer.substring(0, buffer.length - 1);
    } else if (e.which === 13) {
      ipcRenderer.send('submission', buffer);
      buffer = "";
    }
    return flash(buffer);
  });

}).call(this);
